apps/ui/src/components/buttons/buyOrConnect.tsx, apps/ui/src/components/buy/checkout.tsx, apps/ui/src/components/helpers/buyError.tsx, apps/ui/src/hooks/useCheckoutPrice.ts, apps/ui/src/hooks/useCurrency.ts, apps/ui/src/modules/buy/hooks/useBuy.ts, apps/ui/src/modules/buy/page.tsx
**O que foi feito:**
- Foi criado um hook para isolarmos os calculos feitos para a fee.
- Foi ajustado os valores para ser `BN`.
=> [FIX]: Checkout Fee

apps/ui/src/components/buy/checkout.tsx, apps/ui/src/components/helpers/buyError.tsx, apps/ui/src/components/inputs/text.tsx, apps/ui/src/hooks/useCheckoutPrice.ts, apps/ui/src/modules/buy/page.tsx
**What was done:**
- Adjusted responsivity to match with design in figma.
=> [FIX]: Buy Flow

apps/ui/src/modules/home/components/learn-more/page.tsx, apps/ui/src/modules/home/page.tsx, apps/ui/src/routes/childrens.ts, apps/ui/src/routes/index.ts
**What was done:**
- Created route for `Learn More` and added the screen.
=> [FEAT]: Learn More

apps/ui/.env.example, apps/ui/.gitignore, apps/ui/src/components/buy/info.tsx, apps/ui/src/components/card/accountsCard.tsx, apps/ui/src/components/card/addressesCard.tsx, apps/ui/src/components/card/more/resolverCard.tsx, apps/ui/src/components/card/more/tokenCard.tsx, apps/ui/src/components/card/more/validityCard.tsx, apps/ui/src/components/card/ownershipCard.tsx, apps/ui/src/components/card/profileCard.tsx, apps/ui/src/components/helpers/copy.tsx, apps/ui/src/components/helpers/explorer.tsx, apps/ui/src/components/inputs/leftAddon.tsx, apps/ui/src/components/inputs/rightAddon.tsx, apps/ui/src/components/inputs/text.tsx, apps/ui/src/components/inputs/verifiedAccount.tsx, apps/ui/src/components/modal/actionDomainModal.tsx, apps/ui/src/components/modal/transactionDetails.tsx, apps/ui/src/modules/profile/page.tsx, apps/ui/src/types/index.ts
**What was done:**
- Was adjusted the Input to allow words break by changing between a `Container` and a `Input`
- Tried others aproachs but no succeeded.
- Adjusted responsivity for cards and all needed.
=> [FIX]: Input

apps/ui/src/utils/calculator.ts
- Added a verification that if period it's exactly 1 year greater then timestamp, if it is, it returns 1.
=> [FIX]: Transaction Details Periods

apps/ui/src/components/card/addressesCard.tsx, apps/ui/src/components/card/more/resolverCard.tsx, apps/ui/src/components/card/ownershipCard.tsx, apps/ui/src/components/header/index.tsx
- Changed the addresses in inputs from `Bech32` to `B256`
- From `fuels...` to `0x00...`
=> [FEAT]: Fuel Addresses

packages/sdk/src/methods/register.test.ts
- Adjusted the test of `should be able to set primary handle` that was broking
=> [FIX]: Set Primary Handle Test

apps/ui/src/components/card/profileCard.tsx
- Added verification to the button only appears if owner of the handle.
=> [FIX]: Edit Profile Button

apps/ui/src/components/card/more/tokenCard.tsx, apps/ui/src/components/helpers/tokenImage.tsx, apps/ui/src/hooks/useToken.ts
- Adjusted method call into hook `useToken`.
- Removed `useMemo` and added `useQuery` for better approach.
- Removed unecessery load into `TokenImage`
=> [FIX]: Token Card Load

apps/ui/src/components/user/info.tsx
- Added hidden overflow on dropdown `onOpen`.
=> [FIX]: Dropdown Overflow

apps/ui/src/hooks/useResolveOwnerRequests.ts, apps/ui/src/modules/profile/components/profileCardLoadingSkeleton.tsx, apps/ui/src/modules/profile/components/profileCards.tsx, apps/ui/src/modules/profile/page.tsx
https://app.clickup.com/t/86a5g5hpa
=> FIX: Owner address desappearing after refresh the page

apps/ui/src/components/card/more/tokenBody.tsx, apps/ui/src/components/helpers/checkoutCard.tsx, apps/ui/src/components/helpers/tokenImage.tsx, apps/ui/vite.config.ts
https://app.clickup.com/t/86a5htrt8
=> FIX: Adjust nft image spinner on more page

apps/ui/src/hooks/useMetadata.ts
https://app.clickup.com/t/86a5k51p4
=> FIX: Avoid "OnSuccess" case when request goes wrong while buying metadata

apps/ui/src/modules/home/hooks/useHome.ts
https://app.clickup.com/t/86a5k7kwp
=> FIX:  Metadatas aren't being shown on profile page

apps/ui/src/modules/buy/page.tsx, apps/ui/src/modules/home/components/learn-more/page.tsx
https://app.clickup.com/t/86a5kjje9
=> FIX: Add scroll to buy page

apps/ui/src/modules/purchased/page.tsx
https://app.clickup.com/t/86a5mpu21
=> CHORE: Add scroll to success buy handle page

apps/ui/src/components/buy/checkout.tsx, apps/ui/src/components/termsOfUseDialog/index.tsx
https://app.clickup.com/t/86a5mqh2b
=> fix: enabling aggrement button

apps/ui/src/components/inputs/autocomplete.tsx
https://app.clickup.com/t/86a5mqf94
=> fix: problem with spaces and special characters

apps/ui/src/components/buttons/buyOrConnect.tsx, apps/ui/src/components/buy/checkout.tsx, apps/ui/src/components/helpers/buyError.tsx, apps/ui/src/hooks/useCheckoutPrice.ts, apps/ui/src/modules/buy/hooks/useBuy.ts, apps/ui/src/modules/buy/page.tsx, apps/ui/src/modules/home/components/learn-more/page.tsx
https://app.clickup.com/t/86a5mqdmy
=> feat: enable usd button

apps/ui/src/components/user/userAvatar.tsx
Added a timestamp query to the avatar url to avoid browser cache
=> FIX Avatar Upload V2 

apps/marketplace-indexer/config.yaml, apps/marketplace-indexer/schema.graphql, apps/marketplace-indexer/src/EventHandlers.ts, apps/server/app/api/[network]/marketplace/assets/[id]/route.ts, apps/ui/src/hooks/useChainId.ts, apps/ui/src/modules/profile/components/nft/NftSaleCardModal.tsx, packages/marketplace/src/graphql/generated/operations.ts, packages/marketplace/src/graphql/queries/marketplace.graphql
create a new provider instance when user is not logged into wallet
=> fix(useChainId): create provider when user not connect to wallet

apps/ui/src/components/inputs/currency.tsx, apps/ui/src/components/layout/marketplace.tsx, apps/ui/src/components/toast/container.tsx, apps/ui/src/modules/marketplace/collections/page.tsx, apps/ui/src/modules/marketplace/components/banner/collectionBanner.tsx, apps/ui/src/modules/marketplace/components/banner/profileBanner.tsx, apps/ui/src/modules/marketplace/components/banner/root/collectionContent.tsx, apps/ui/src/modules/marketplace/components/banner/root/collectionsContent.tsx, apps/ui/src/modules/marketplace/components/collectionItem.tsx, apps/ui/src/modules/marketplace/components/collectionList.tsx, apps/ui/src/modules/marketplace/components/listHeader.tsx, apps/ui/src/modules/marketplace/components/marketplaceHeader.tsx, apps/ui/src/modules/marketplace/components/martketplaceEmptyState.tsx, apps/ui/src/modules/marketplace/components/mintPanel/index.tsx, apps/ui/src/modules/marketplace/components/orderList.tsx, apps/ui/src/modules/marketplace/page.tsx, apps/ui/src/modules/marketplace/profile/components/profileNfts.tsx, apps/ui/src/modules/marketplace/profile/page.tsx, apps/ui/src/modules/profile/components/nft/NftCardModal/NftFormStep.tsx, apps/ui/src/modules/profile/components/nft/NftCardModal/index.tsx, apps/ui/src/modules/profile/components/nft/NftCardSaleForm.tsx, apps/ui/src/modules/profile/components/nft/NftSaleCardModal/NftDetailsStep.tsx, apps/ui/src/modules/profile/components/nft/NftSaleCardModal/NftFormStep.tsx, apps/ui/src/modules/profile/components/nft/NftSaleCardModal/index.tsx
Nft card modal, header, collection list card, marketplace background and responsiveness
=> Marketplace Design Adjustments V2

apps/ui/src/modules/profile/components/nft/NftSaleCardModal/NftFormStep.tsx
=> fix(order): parse units with asset decimals

apps/ui/src/modules/marketplace/components/collectionList.tsx, apps/ui/src/modules/marketplace/components/listHeader.tsx, apps/ui/src/modules/marketplace/page.tsx
Set "Sales" as default filter in garage home page
=> CHORE: Set "Sales" as default filter in garage home page
